server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/novashop_db
    username: root
    password: 2104
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# Configuracion JWT (version final)
jwt:
  secret:
    key: esta-es-mi-clave-super-secreta-para-dev-123456789012345678901234567890
  expiration:
    access-token: 3600000  # 1 hora (debe coincidir con JwtService)

# Elimina la seccion CORS de aquí (lo manejaremos en SecurityConfig)

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.fescode: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/novashop_prod
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jwt:
    secret:
      key: ${JWT_SECRET}