server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/novashop_db_v2
    username: root
    password: 2104
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  jackson:
    serialization:
      fail-on-empty-beans: false

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

logging:
  level:
    root: warn
    org:
      springframework:
        security: TRACE  # Para depurar Spring Security
        web: DEBUG       # Para ver peticiones HTTP
      hibernate:
        SQL: DEBUG                   # Consultas SQL
        type.descriptor.sql.BasicBinder: TRACE  # Parámetros de queries
    com:
      fescode: DEBUG  # Tus clases personalizadas

jwt:
  secret: "n/EUgwkn4/cTiWbB8WJasw==uEyKhnf7iQDNv9jmiKe6LAEo3p9TFA41kOLjZPW6"
  expiration: 86400000  # 24 horas en milisegundos

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/novashop_prod
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jwt:
    secret:
      key: ${JWT_SECRET}